<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use App\Traits\HasFullName;
use App\Traits\HasSearchable;
use App\Traits\NormalizesEmail;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable, HasFullName, HasSearchable, NormalizesEmail;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'student_id',
        'faculty_id',
        'first_name',
        'middle_name',
        'last_name',
        'contact_number',
        'email',
        'google_id',
        'avatar',
    ];

    /**
     * Fields that should be searchable.
     */
    protected array $searchableFields = ['first_name', 'last_name', 'email', 'student_id', 'faculty_id'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'password_changed_at' => 'datetime',
            'must_change_password' => 'boolean',
            'is_temporary_password' => 'boolean',
        ];
    }

    /**
     * Get the roles associated with this user (many-to-many).
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'role_user')
            ->withTimestamps();
    }

    /**
     * Get the primary role (for backward compatibility).
     * Returns the first role or null.
     */
    public function role(): ?Role
    {
        return $this->roles()->first();
    }

    /**
     * Get the faculty profile linked to this user (if any).
     */
    public function faculty(): BelongsTo
    {
        return $this->belongsTo(Faculty::class, 'faculty_id', 'faculty_id');
    }

    /**
     * Get the researches uploaded by this user.
     */
    public function uploadedResearches(): HasMany
    {
        return $this->hasMany(Research::class, 'uploaded_by');
    }

    /**
     * Get the researches archived by this user.
     */
    public function archivedResearches(): HasMany
    {
        return $this->hasMany(Research::class, 'archived_by');
    }

    /**
     * Get the compiled reports generated by this user.
     */
    public function compiledReports(): HasMany
    {
        return $this->hasMany(CompiledReport::class, 'generated_by');
    }

    /**
     * Get the research access logs associated with this user.
     */
    public function researchAccessLogs(): HasMany
    {
        return $this->hasMany(ResearchAccessLog::class, 'user_id');
    }

    /**
     * Get the keyword search logs performed by this user.
     */
    public function keywordSearchLogs(): HasMany
    {
        return $this->hasMany(KeywordSearchLog::class, 'user_id');
    }

    /**
     * Get the research entry logs this user performed (create/update/archive).
     */
    public function researchEntryLogs(): HasMany
    {
        return $this->hasMany(ResearchEntryLog::class, 'modified_by');
    }

    /**
     * Get the audit logs where this user performed the modification.
     */
    public function userAuditLogs(): HasMany
    {
        return $this->hasMany(UserAuditLog::class, 'modified_by');
    }

    /**
     * Get the audit logs targeting this user account.
     */
    public function userAuditLogsTargeting(): HasMany
    {
        return $this->hasMany(UserAuditLog::class, 'target_user_id');
    }

    /**
     * Get the faculty audit logs where this user performed the modification.
     */
    public function facultyAuditLogs(): HasMany
    {
        return $this->hasMany(FacultyAuditLog::class, 'modified_by');
    }

    /**
     * Check if user has a specific role (supports multiple roles)
     */
    public function hasRole(string $role): bool
    {
        return $this->roles()->where('name', $role)->exists();
    }

    /**
     * Check if user has any of the given roles
     */
    public function hasAnyRole(array $roles): bool
    {
        return $this->roles()->whereIn('name', $roles)->exists();
    }

    /**
     * Check if the user is a student.
     */
    public function isStudent(): bool
    {
        return $this->hasRole('Student');
    }

    /**
     * Check if the user is an administrator.
     */
    public function isAdministrator(): bool
    {
        return $this->hasRole('Administrator');
    }

    /**
     * Check if the user is faculty.
     */
    public function isFaculty(): bool
    {
        return $this->hasRole('Faculty');
    }

    /**
     * Check if the user is MCIIS staff.
     */
    public function isMCIISStaff(): bool
    {
        return $this->hasRole('MCIIS Staff');
    }

    /**
     * Check if user is admin or staff
     */
    public function isAdminOrStaff(): bool
    {
        return $this->isAdministrator() || $this->isMCIISStaff();
    }
    
    /**
     * Check if user needs to change password
     */
    public function needsPasswordChange(): bool
    {
        return $this->must_change_password && $this->isAdminOrStaff();
    }

    /**
     * Mark that user has changed their password
     */
    public function markPasswordChanged(): void
    {
        $this->forceFill([
            'must_change_password' => false,
            'is_temporary_password' => false,
            'password_changed_at' => now(),
        ])->save();
    }

    /**
     * Set temporary password for admin/staff users
     */
    public function setTemporaryPassword(string $password): void
    {
        // Let the 'hashed' cast hash the raw password
        $this->forceFill([
            'password' => $password,
            'must_change_password' => true,
            'is_temporary_password' => true,
            'password_changed_at' => null,
        ])->save();
    }

    /**
     * Format contact number for display
     */
    public function getFormattedContactNumberAttribute(): ?string
    {
        if (!$this->contact_number) {
            return null;
        }

        $clean = preg_replace('/[^0-9]/', '', $this->contact_number);
        
        if (strlen($clean) === 11 && substr($clean, 0, 2) === '09') {
            return '+63 ' . substr($clean, 1);
        }
        
        if (strlen($clean) === 12 && substr($clean, 0, 2) === '63') {
            return '+63 ' . substr($clean, 2);
        }
        
        return $this->contact_number;
    }

    /**
     * Format student ID for display
     */
    public function getFormattedStudentIdAttribute(): ?string
    {
        if (!$this->student_id) {
            return null;
        }

        $clean = preg_replace('/[^0-9]/', '', $this->student_id);
        
        if (strlen($clean) >= 8) {
            $year = substr($clean, 0, 4);
            $number = substr($clean, 4);
            return $year . '-' . str_pad($number, 5, '0', STR_PAD_LEFT);
        }
        
        return $this->student_id;
    }
}
